language: scala

scala:
  - "2.12.15"
  - "2.13.7"

sudo: false

script:
  - sbt "++$TRAVIS_SCALA_VERSION clean" "++$TRAVIS_SCALA_VERSION test"

after_success:
  - "[[ \"$TRAVIS_REPO_SLUG\" == \"wix/wix-http-testkit\" ]] && [[ \"$TRAVIS_BRANCH\" == \"master\" ]] && { sbt \"++$TRAVIS_SCALA_VERSION publish\"; };"

jdk:
  - oraclejdk8

env:
  global:
  - secure: naUSlGUX60zmIJv3+Vevk0+2UppS091KywKn1Dzdc9+cWoX1D2hqbFclRgDaekKrN79UsT/PxUOYCK87Xm9MHAd+jwlAnRxdaSpVKYjButKbZOa+SnLyrv/kKt50rJouOPJ1V1aQ0c4NxCYQrmevQDG/bqOoPucoqUpo/MTizbeQ1mvxz0441RR3it1tBaL6JY4XtH9iJylGqhVVlguH8JLssJrGhUqjQo6yg2Jjg8m17oxbZ5kRlnrxWJKe8X0k5w9QgZIgOLBGZcppSTqE1BmR0U18Flpm+y8NeTpfziEZ39SQv0Yg9fu0mJDi0Q2327X+2fqXIPC2GHVelpLz7d5w1QgPQQMeqJcuMEqe9hO4HeFP+B9Nk6gBfXcWqXklgAc9ipmm/4sGvYMMW1oemmt5pHAoIpVv5R2ubW1coOrKRv3Vacl2uPU1tLp0NL2oI68YM2UYSAmTI2zgpiyJ191QDGMXAqocTBOuNDA68F3CJylZg1emyxcrNzjSdXF7jQqUmJjCbcyyv0OEYE9ORyw1nO++vGBbRs9jUC8ZxDKrfYxJyIk1J8a+idjLAvuNWqshD+QYT/J2tTVjv8XRDwi/OoQDXFCwg0CK7sVYqtQeSn/eN+5oNVlqrhq+0Chl01y+CDKCzGSKSOXmAf9I1nnGA8usr3rUfBrC/EwJGWw=
  - secure: NLKwnydKd/aXoJAwxvKGS0Jp+4LhZubV7clrqnakEdzYBXox+d8GiEp1ev5za7weo4Z2hH+CZcbJY7/JcPpNNIsLayBDyaTQso5HrUxBj5GEc1GNF0BTS547boDMGqzrtayxFQ1sztnYbdh0mk+sM7Dba28r/ZDOMDiWKyM+PUbT8mXmOWmN2nNyw88bpGSB3DWKj5Pv4t3tBEKgWfpgN8365xNfvbQfu8t8KEGvb0IsMdlUwuUyAqK7S+WQLWxjk2VeI9sfbsCF9ICs3nbN7OZnQ3VKqnHFK1BDnNag+eBGSqSpGwxoN4M9kTCkofVXixC7ymtbEQSzM03xSNQIWa2JHq3qUZxUwEe+3nm9Pyi4s1PkZKhyal2+DFH6H3byQQOYuArYee8N9KeJKeHLe9to539XYI/HLA/rGdD41PwLnXV8IytT3Lt3AFqQ66W2UtN2fikpN99PbmcIciAlvOxEAI+cY6jZtDI+QbAwDBez+5IidDsSdvKwW3PNLSLDNv1WYdVDvyBJA/c4R9rM8BsWG77JA0dCMntO7pt3jN/j7qXFzAyU74BzNrVlpZsPoMTxgYqQRPhW+XapN0XFjM0bVwn2G4J0WDBY103vzAUY0pxebrrzPu85k+JsVHvoOkTHdrocmYHRTut2YA+m611Kv1u/8ArnhMHfOnyE9ME=

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
    - "$HOME/.sbt/launchers/"

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

dist: trusty